# Generated by Django 5.1.3 on 2025-08-30 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipe", "0001_initial"),
        ("tag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("introducao", models.TextField()),
                ("resumo", models.TextField()),
                ("referencial_teorico", models.TextField()),
                ("desenvolvimento", models.TextField()),
                ("resultados", models.TextField()),
                ("conclusao", models.TextField()),
                ("referencias", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="equipe.equipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjetoTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.projeto",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tag.tag"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="tags",
            field=models.ManyToManyField(
                related_name="projetos", through="projeto.ProjetoTag", to="tag.tag"
            ),
        ),
    ]
