# Generated by Django 5.1.3 on 2025-09-09 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projeto", "0001_initial"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comentario",
                    models.TextField(blank=True, null=True, verbose_name="Feedback"),
                ),
                (
                    "data_avaliacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Avaliação"
                    ),
                ),
                (
                    "nota_final",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Nota Final",
                    ),
                ),
                (
                    "avaliador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_feitas",
                        to="usuario.usuario",
                        verbose_name="Avaliador",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="projeto.projeto",
                        verbose_name="Projeto",
                    ),
                ),
            ],
        ),
    ]
