# Generated by Django 5.1.3 on 2025-09-09 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("avaliacao", "0001_initial"),
        ("criterio", "0001_initial"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaCriterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.PositiveIntegerField()),
                ("comentario_criterio", models.TextField(blank=True, null=True)),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_criterios",
                        to="avaliacao.avaliacao",
                    ),
                ),
                (
                    "avaliador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_criterios",
                        to="usuario.usuario",
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_criterios",
                        to="criterio.criterio",
                    ),
                ),
            ],
        ),
    ]
