# Generated by Django 5.1.3 on 2025-08-26 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("avaliacao", "0001_initial"),
        ("criterio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaCriterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.PositiveIntegerField()),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_dos_criterios",
                        to="avaliacao.avaliacao",
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_recebidas",
                        to="criterio.criterio",
                    ),
                ),
            ],
            options={
                "unique_together": {("avaliacao", "criterio")},
            },
        ),
    ]
