# Generated by Django 5.1.3 on 2025-08-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notacriterio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notacriterio",
            name="nota",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
