# Generated by Django 5.1.3 on 2025-09-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("criterio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Barema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota_obtida", models.PositiveIntegerField()),
                (
                    "criterios",
                    models.ManyToManyField(
                        related_name="baremas", to="criterio.criterio"
                    ),
                ),
            ],
        ),
    ]
